web/Agent/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

from django.urls import include, path
from django.conf.urls import url


urlpatterns = [
     path('', views.AgentHome, name='Agent'),
     path('Agentupload/', views.Agentupload, name='Agentupload'),
     path('NewAgent/', views.NewAgent, name='NewAgent'),
     path('Agentupdate/', views.Agentupdate, name='Agentupdate'),
     path('Agenthome/', views.Agenthome, name='Agenthome'),
     path('upload/', views.upload_file, name="upload_file"),
     path('Become-Agent/', views.SignupAgent, name="SignupAgent"),
     path('Ekosodin/', views.ekosodin, name="ekosodin"),
     path('BDPA/', views.bdpa, name="BDPA"),
     path('osasoge/', views.osasoge, name="osasoge"),
     path('UpdateProfile/<user_id>/', views.UpdateProfile, name="UpdateProfile"),
     path('UpdateProfilePicx/<user_id>/', views.upload_profilePicx, name="UpdateProfilePicx"),
     path('delete/<id_image>/', views.delete, name='delete'),
     path('view_Agentproperty/<str:property_id>//<str:username>/', views.show_Agentproperty, name='view_Agentproperty'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/web/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moborise.urls')),
    path('Agent/', include(('Agent.urls','Agent' ), namespace='Agent')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/Agent/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.contrib.auth.models import AbstractUser, User
from django.db.models.signals import post_save, post_delete, post_init
from django.dispatch import receiver

#from rest_framework.authtoken.models import Token 
import os




 

# Create your models here.


def user_directory_path(instance, filename, **kwargs):
    file_path = 'gallery/{username}/{filename}'.format( username = str(instance.author.username), filename=filename)
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return file_path


class Agentuploads(models.Model):
    file = models.FileField(upload_to=user_directory_path, null=False, blank=False)
    
    filename = models.CharField(max_length = 100, blank=True)
    username = models.CharField(max_length = 100)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=False, blank=False)
    property_Name = models.CharField(max_length = 100)
    property_Address = models.CharField(max_length = 100)
    property_Location = models.CharField(max_length = 100)
    property_Description = models.CharField(max_length = 100)
    property_Type = models.CharField(max_length = 100)
    
    price = models.IntegerField(default=0)
    verify = models.TextField(default='Not verified' ,max_length = 100)

    
    uploaded_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length = 150, unique=False)
  

    def __unicode__(self):
        return '%s' % (self.file.name)

    def delete(self, *args, **kwargs):
        os.remove(os.path.join(settings.MEDIA_ROOT, self.file.name))
        if self.uploadsfile:
            self.uploadsfile.delete()
        Agentuploads.delete()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.property_Description, allow_unicode=True)
        super(Agentuploads, self).save(*args, **kwargs)


class uploadsfile(models.Model):
    post = models.ForeignKey(Agentuploads, related_name="picture", on_delete=models.CASCADE,)
    file = models.FileField(upload_to='gallery/', null=True, blank=True)
   


# @receiver(post_save, sender= settings.AUTH_USER_MODEL)
# def create_auth_token(sender, instance=None, created=False, **kwargs):
#     if created:
#         Token.objects.create(user=instance)



# Create your models here.

web/Agent/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Agentuploads
from moborise.models import ProfilPicx, UserType
Property_type= [
    ('One room', 'One room'),
    ('Self Contain', 'Self Contain'),
    ('2 Bedroom', '2 Bedroom'),
    ('3 Bedroom', '3 Bedroom'),
    ]
Location= [
    ('Benin', 'Benin'),
    ('Lagos', 'Lagos'),
    ('Delta', 'Delta'),
   
    ]

propertyy_Location= [
    ('BDPA', 'BDPA'),
    ('Ekosodin', 'Ekosodin'),
    ('Osasoge', 'Osasoge'),
   
    ]

INTEGER_CHOICES= [tuple([x,x]) for x in range(1,500)]

class ProfileUploadForm(forms.Form):
    
    img = forms.FileField(widget=forms.ClearableFileInput(attrs={'placeholder':'input your password', 'class': 'custom-file-input',  'oninput' : 'input_filename();',  }))
    
    


class AgentUploadFileForm(forms.ModelForm):
    
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'placeholder':'input your password', 'class': 'upload-input',   'oninput' : 'input_filename();','multiple': 'multiple', 'accept' : 'image/jpg, image/gif/png, image/jpeg', }))

    
    property_Address = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Name of Address' }))
    property_Name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Name of Property' }))
    property_Location = forms.CharField(widget=forms.Select(choices=propertyy_Location))
    property_Description = forms.CharField(label='Describe the Property', widget=forms.Textarea(attrs={"rows":5, "cols":35 ,'placeholder':'About the property'}))
    property_Type = forms.CharField(label='Type of Property', widget=forms.Select(choices=Property_type))
    prize = forms.IntegerField(label='Amount to rent', widget=forms.Select(choices=INTEGER_CHOICES))

    

    def form_valid(self, form):
         obj = form.save(commit=False)
         if self.request.FILES:
            for f in self.request.FILES.getlist('file'):
                obj = self.model.objects.create(file=f)
                
                return super(AgentUploadFileForm, self).form_valid(form)



    
    class Meta:
        model = Agentuploads
        fields = ('file' ,'property_Name', 'property_Location', 'property_Description', 'property_Type', 'prize')




class AgentSignUpForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'First Name' }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Last Name' }))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'username' }))
    email = forms.EmailField(max_length=254, label='email', help_text='Required. Inform a valid email address.', widget= forms.TextInput
                           (attrs={'placeholder':'Email'}))
    Location = forms.CharField(label='Type of Property', widget=forms.Select(choices=Location))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'input your password' }))
    password2= forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'confirm password' }))

    

    class Meta:
        model = User
        fields = ('first_name', 'last_name','username' , 'email', 'password1', 'password2', )
        
class AgentLoginUpForm(AuthenticationForm):
    username2 = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'username ..' }))
    
    Loginpassword = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':' password' }))
    

    class Meta:
        model = User
        fields = ('username' , 'password', )

web/Agent/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.contrib import messages 
from django.http import HttpResponse
from moborise.models import  ProfilPicx
from .models import Agentuploads, uploadsfile
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.models import User
from django.http import JsonResponse
from .forms import AgentUploadFileForm, AgentSignUpForm, ProfileUploadForm
import os
from moborise.forms import LoginUpForm
from moborise.models import UserType, Comment
from django.contrib.auth.decorators import login_required
 
# Create your views here.
def  SignupAgent(request):
    if request.method == 'POST':
        form = AgentSignUpForm(data=request.POST, initial={'role': request.user.UserType.role}, \
                            instance=request.user.UserType)
        
        password1 = request.POST['password']
        password = make_password(password1)
        if User.objects.filter(username=username).exists():
            return JsonResponse({'username_error':'username already exists'})

        if User.objects.filter(email=email).exists():
            return JsonResponse({'email_error':'email already in use'})
        
        if len(password1) < 5:
            return JsonResponse({'password_error':'password should be greater than 5'})
        
        if form.is_valid() :
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.email = form.cleaned_data['email']
            
            user.save()
            user.userprofile.save()
        
        return JsonResponse({'success':'success'})
    else:

        form = AgentSignUpForm(data=request.POST,)
        form2 = LoginUpForm(data=request.POST)
    
   
    return render(request, 'AgentSignup.html', {'form2': form2,'form': form, 'media_url': settings.MEDIA_URL, 'media_root': settings.MEDIA_ROOT,})

def loginUser(request):

    form = LoginUpForm()
      
    return render(request, 'login_ajaxAgent.html',  {'form': form,})



@login_required(login_url='/')
@csrf_exempt
def upload_profilePicx(request, user_id):
    

    if request.user.is_authenticated == True:
        user = request.user
        print(user)
       
        tests = ProfilPicx.objects.get(user_id = user_id,)
        tests.delete()
        if request.method == 'POST':
            obj = User.objects.get(id=user_id)
            form = ProfileUploadForm(request.POST, request.FILES)
            if form.is_valid():
                obj = User.objects.get(id=user_id)
                profile = obj.profilePicx
                profile.img = form.cleaned_data['img']
                profile.save()
                
            print('N')
            messages.add_message(request, messages.SUCCESS, 'Profile Picx Uploaded')
            
            return redirect('Agent:Agentupdate')
        return redirect('home')
    else:
        form = ProfileUploadForm()
    messages.add_message(request, messages.SUCCESS, 'Error')
    return redirect('home')  

@login_required(login_url='/')
@csrf_exempt
def UpdateProfile(request, user_id,):
    
    if request.method == 'POST':
        About = request.POST['about']
        Phone = request.POST['phone']
        Whatsapp_num = request.POST['whatsapp_num']
        Business_name = request.POST['business_name']
        Employment_stat = request.POST['employment_stat']
        
        print(Whatsapp_num)

        obj = User.objects.get(id=user_id)

        obj.profile.About=About
        obj.profile.phone=Phone
        
        obj.profile.whatapp_number=Whatsapp_num
        obj.profile.Business_Name=Business_name
        obj.profile.Employment_status=Employment_stat

        obj.profile.save()

      
    return render(request, 'login_ajaxAgent.html', )

@login_required(login_url='/')
def AgentHome(request):
    
    
   
    return render(request, 'Agent.html', {'media_url': settings.MEDIA_URL, 'media_root': settings.MEDIA_ROOT,})
@login_required(login_url='/')
def Agentupload(request):
    form = AgentUploadFileForm(data=request.POST)
    tests = User.objects.all()
    context = {'tests': tests,'media_url': settings.MEDIA_URL,'form': form, 'media_root': settings.MEDIA_ROOT,}
    template = 'upload.html'

    

    return render(request, template, context)
@login_required(login_url='/')
def Agentupdate(request):
    form = ProfileUploadForm(data=request.POST)
    tests = User.objects.get(username=request.user)
    listing = Agentuploads.objects.filter(username=request.user)
    context = {'tests': tests,'listing': listing, 'form': form,'media_url': settings.MEDIA_URL, 'media_root': settings.MEDIA_ROOT,}
    template = 'update.html'
    

    return render(request, template, context)

@login_required(login_url='/')
def Agenthome(request):
    
    tests = User.objects.all()
    context = {'tests': tests,'media_url': settings.MEDIA_URL, 'media_root': settings.MEDIA_ROOT,}
    template = 'Agenthome.html'
    

    return render(request, template, context)
@login_required(login_url='/')
def ekosodin(request):
    
    tests = Agentuploads.objects.all().filter(username = request.user, property_Location='Ekosodin')
    context = {'tests': tests,'media_url': settings.MEDIA_URL, 'media_root': settings.MEDIA_ROOT,}
    template = 'listings/ekosodin.html'
    

    return render(request, template, context)


@login_required(login_url='/')
def osasoge(request):
    
    tests = Agentuploads.objects.all().filter(username = request.user, property_Location='Osasoge')
    context = {'tests': tests,'media_url': settings.MEDIA_URL, 'media_root': settings.MEDIA_ROOT,}
    template = 'listings/osasoge.html'
    

    return render(request, template, context)


@login_required(login_url='/')
def bdpa(request):
    
    tests = Agentuploads.objects.all().filter(username = request.user, property_Location='BDPA')
    context = {'tests': tests,'media_url': settings.MEDIA_URL, 'media_root': settings.MEDIA_ROOT,}
    template = 'listings/bdpa.html'
    

    return render(request, template, context)
def show_Agentproperty(request, property_id, username):
    
    user = get_object_or_404(User, username=username,)
    
    propertyy = Agentuploads.objects.get(id=property_id)
    comment = Comment.objects.filter(post_id=property_id)
    
    return render(request, 'view_agentUpload.html', {'comment': comment,"person":user,'property': propertyy, 'media_url': settings.MEDIA_URL,})

@login_required(login_url='/')
def upload_file(request):
    

    if request.user.is_authenticated == True:
        user = request.user
        print(user)
        if request.method == 'POST':
            form = AgentUploadFileForm(request.POST, request.FILES)
            files = request.FILES.getlist('file')
            
            if form.is_valid():
                new_obj = Agentuploads(file=form.cleaned_data['file'],property_Name=request.POST['property_Name'], property_Location=request.POST['property_Location'] , property_Type=request.POST['property_Type'], property_Description=request.POST['property_Description'], property_Address=request.POST['property_Address'], username=user, author=request.user)
                new_obj.save()

                for f in files:
                    gallery = uploadsfile(post=new_obj, file=f)
                    gallery.save()
                messages.add_message(request, messages.SUCCESS, 'image succesfully uploaded')
                return redirect('Agent:Agentupload')
            else:
                print(request.POST)
                print(form.errors)
                print(form.non_field_errors)
                return redirect('index')
        
    else:
        form = AgentUploadFileForm()
    messages.add_message(request, messages.SUCCESS, 'Error')
    return redirect('home')  


@login_required(login_url='/')
def NewAgent(request):
    if request.method == 'POST':
        
        
        firstname = request.POST['name']
        lastname = request.POST['lastname']
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password']
        password = make_password(password1)
        if User.objects.filter(username=username).exists():
            return JsonResponse({'username_error':'username already exists'})

        if User.objects.filter(email=email).exists():
            return JsonResponse({'email_error':'email already in use'})
        
        if len(password1) < 5:
            return JsonResponse({'password_error':'password should be greater than 5'})
        
        user = User.objects.create(
            first_name = firstname,
            last_name = lastname,
            username = username,
            email = email,
            password = password,
            
        )
        user =  User.objects.get(username=request.POST['username'],)
        
        profile = user.profile # because of signal and one2one relation
        
        profile.role = 'Agent'
        profile.save()
    
        
        return JsonResponse({'success':'success'})

@login_required(login_url='/')
def delete(request, id_image):
    user = request.user
    file_type = 'image'
   

    testss = Agentuploads.objects.get(id = id_image,)
    testss.delete()

    # messages.add_message(request, messages.SUCCESS, f'image {file_name} successfully deleted')
    return redirect('Agent:Agentupload')

web/Agent/templates/listings/bdpa.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>MOlite</title>
    {% load static %}

    <link rel="icon" href="{% static 'molite.png' %}" type="image/x-icon">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    <link rel="stylesheet" href="{% static 'style2.css' %}">
    
 
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  

    <!-- Latest compiled JavaScript -->
    <script>



    </script>
    <style>

    html, body {
    scroll-behavior: smooth;
        }
        body {
        background: #eee;
        font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
        font-size: 14px;
        color:#000;
        height: 100vh;
        padding: 0;
        
        }
        nav{
        
        
        
        background-size:cover;
        background-width: 100px;
        background-position: absolute;
        font-family: Arial;
    }
    </style>



</head>
<body>

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

<div id="myModal" class="modall">
      <!-- Modal content -->
      <div style="background: #343a40;" class="modall-content" id="modall-content">
        <span class="close">&times;</span>
        <a id="back" style="cursor: pointer;">back</a>
<form id="upload_Form" method="POST" action="{% url 'Agent:upload_file'  %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="frame">
	      
		

        <div class="dropzone">
          <img src="http://100dayscss.com/codepen/upload.svg" class="upload-icon" />
          {{ form.file }}
        </div>
        <div class="title">
          Drop file to upload
        </div>
        <div style="color: #fff;" id="file_input_label"></div>
        <p>Property Name</p>
        {{ form.property_Name }}<br><br>
        <p>Property Location</p>
        {{ form.property_Location }}<br><br>
        <p>Property Address</p>
        {{ form.property_Address }}<br><br>
        <p>Property Type</p>
        {{ form.property_Type }}<br><br>
        <p>Describe this property</p>
        {{ form.property_Description }}<br><br>
        <p>Property Price</p>
          {{ form.prize }}
          
        <br>
        <br>
        <button class="btn btn-primary" type="submit" id="upload_btn" onclick="upload()">UPLOAD Property</button>
                <br>
               

                <button class="btn btn-primary d-none" id="loading_btn" type="button" disabled>
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            Uploading...
          </button>

           <div style="margin-top: 20px;" id="progress" class="progress d-none">
                  <div id="progressBar" class="progress-bar " role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
                </div>
              </form>

      
    </form>


      </div>

</div>
</div>






<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="postion: fixed !important; z-index: 12; width: 100%;">
      <a class="navbar-brand" href="/"><img height="30" width="100" src="{% static 'molite1.jpg' %}"></a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navb">
        <ul class="navbar-nav justify-content-center mr-auto">
        {% if user.is_authenticated %}
          <li><a class="nav-link" id="home" href="">Home</a></li>
            <li><a class="nav-link" href="#">Locations</a></li>
            <li><a class="nav-link" href="#">Vacancies</a></li>
            <li><a class="nav-link" href="#">Info</a></li>
            {% if request.user.profile.role == 'Agent'%}
            <li><a class="nav-link" href="{% url 'Agent:Agent'  %}">Agent Home</a></li>
            {% endif %}
            <li><a class="nav-link" href="{% url 'logout'  %}">Logout</a></li>
             
            {% else %}
            <li><a class="nav-link" id="home" href="">Home</a></li>
            <li><a class="nav-link" href="#">Locations</a></li>
            <li><a class="nav-link" href="#">Vacancies</a></li>
            <li><a class="nav-link" href="#">Info</a></li>
            <li><a style="cursor: pointer;" class="nav-link" id="myBtn" >Sign up or Login </a></li>
            <li><a class="nav-link" href="#">About us</a></li>
            {% endif %}
        </ul>
        <form action="/search" class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" required type="search" autocomplete="off"  name="q" aria-label="Search" placeholder="Search for vacancies...">
          <button class="btnn" style="" type="button"><i style="color: #000; " class="fa fa-search" aria-hidden="true"></i></button>
        </form>
      </div>
    </nav>
    {% if messages %}

    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}  alert-dismissible fade show"{% endif %} role="alert">
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}

{% endif %}
<div class="home-container" id="content">


    <div class="side-bar">
        
        <div   class="side-item" ><a href="{% url 'Agent:Agenthome'  %}" class="tablink" ><i style="font-size: 50px; position: block;" class="fa fa-user-circle-o" aria-hidden="true"></i> Home</a></div>
        <div class="side-item"><a href="{% url 'Agent:Agentupdate'  %}" class="tablink"  ><i style="font-size: 50px;" class="fa fa-inbox" aria-hidden="true"></i>Profile</a></div>
        <div style="background: #343a40; pointer-events: none;"  class="side-item"><a disabled href="{% url 'Agent:Agentupload'  %}" class="tablink" ><i style="font-size: 50px;" class="fa fa-cloud-upload" aria-hidden="true"></i>Listings</a></div>
        {% comment %} <div onclick="openPage('News', this, '#343a40')" class="side-item"><a href="#" class="tablink"  ><i style="font-size: 50px;" class="fa fa-cog" aria-hidden="true"></i>Settings</a></div> {% endcomment %}

        
    </div>



      <div id="Navigation" class="main-content">
                <div class="ajaxProgress" style="display:none; position: absolute; top: 50%; left: 50%; margin: -50px 0px 0px -50px;">
                    <img src="{% static 'ajax-loader.gif' %}" >
                </div>
                <div id="Navigation_content">
                    <div class="row">
    {% for property in tests %}

                <div class="col-lg-3 col-md-3 col-sm-6 col-6">
                                    <div  class="card mb-4">
                                        <a  href="{% url 'Agent:view_Agentproperty' property.id property.username %}">
                                            <div class="card-img-top"
                                                ><img src="{{property.file.url}}" style=" height:150px;width:100% "></div>
                                        
                                        <div  class="card-body">
                                            <span  id="view{{ property.id }}"  style="text-size:10px; color: black;"><span style='font-weight: 20px;'>Location: </span>{{property.property_Location}}
                                            <br>
                                            <span style='font-weight: 20px;'>Property Name: </span>{{property.property_Name}}</span></a>
                                            <br>
                                            <span class="text-warning">Not verified</span>
                                            
                                        </div>
                                    </div>
                                    <!-- /.card -->
                        
                </div>                

    


              {% endfor %}
              </div>
    
                </div>
        </div>
        <br>

       
      
      </div>

<script>
$("#myBtnn").click(function(){
      $('#myModal').show()
  
});



$(".close").click(function(){
      $('#myModal').hide()
  
});


$(window).click(function(e) {
    var target = $( event.target );
    if ( target.is( "#myModal" ) ) {
    $('#myModal').hide();
  }

});



</script>


<script src="{% static 'scripts.js' %}"></script>
<script>
var input = document.getElementById("id_file");
var file_input_label = document.getElementById("file_input_label");


function input_filename() {

  file_input_label.innerText = input.files[0].name;


}
</script>




  </body>
  </html>