web/moborise/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

from django.urls import include, path
from django.conf.urls import url


urlpatterns = [
    path('', views.index, name='index'),
    path('load_index/', views.load_index, name='load_index'),
    path('home/', views.home, name='home'),
    path('logout/', views.logout_request, name="logout"),
    path('search/', views.search, name="search"),
    path('AgentReg/', views.NewUser, name="NewUser"),
    path('Login/', views.loginreq, name="Login"),
    path('reply/', views.replyy, name="reply"),
    path('Userlogin/', views.loginUser, name="UserLogin"),
    path('signup/', views.signup, name="Signup"),
    path('view_property/<str:property_id>//<str:username>/', views.show_property, name='view_property'),
    path('comment/<str:property_id>//<str:username>/', views.comment, name='comment'),
    path('reply/<str:comment_id>//<str:username>/', views.send_reply, name='send_reply'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/web/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moborise.urls')),
    path('Agent/', include(('Agent.urls','Agent' ), namespace='Agent')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/moborise/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractUser, User
from django.db import models
from django.db.models.signals import post_save, post_delete, post_init
from django.dispatch import receiver
from django.conf import settings
import os
from Agent.models import Agentuploads

def user_directory_path(instance, filename, **kwargs):
    file_path = 'gallery/profile/{filename}'.format( filename=filename)
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return file_path

class UserType(models.Model):
    user = models.OneToOneField(User, related_name="profile", on_delete=models.CASCADE,)
    About = models.CharField(max_length = 100, )
    phone = models.CharField(max_length = 100, )
    whatapp_number = models.CharField(max_length = 100, )
    Business_Name = models.CharField(max_length = 100, )
    Employment_status = models.CharField(max_length = 100, )
    Facebook_link = models.CharField(max_length = 100, )
    Successfully_trans = models.IntegerField(default=0,)
    role = models.CharField(max_length = 100, )
    img = models.FileField(upload_to = "gallery/profile/")
    # url = models.URLField("Website", blank=True)
    

    def __unicode__(self):
        return self.role

    def save(self, *args, **kwargs):
        if not self.role:
            self.role = 'U'
        return super().save(*args, **kwargs)

class Comment(models.Model):
    author = models.ForeignKey(User, related_name='TheUser', on_delete=models.CASCADE)
    text = models.TextField()
    post_id = models.IntegerField(default='0')
    Username = models.CharField(max_length = 100, )
    time = models.CharField(max_length = 100, )
    created_date = models.DateTimeField(auto_now_add=True)
    to = models.CharField(max_length = 100, )
    

    def __str__(self):
        return self.text

class Reply(models.Model):
    rep = models.ForeignKey(Comment, related_name="reply", on_delete=models.CASCADE)
    reply = models.TextField()
    Username = models.CharField(max_length = 100, )
    post_id = models.IntegerField(default='0')
    time = models.CharField(max_length = 100, )
    created_date = models.DateTimeField(auto_now_add=True)
    to = models.CharField(max_length = 100, )
    

    def __str__(self):
        return self.text

class ProfilPicx(models.Model):
    user = models.OneToOneField(User, related_name="profilePicx", on_delete=models.CASCADE,)
    
    img = models.FileField(upload_to = '', null=False, blank=False)

    def save(self, *args, **kwargs):
        if not self.img:
            self.img = 'U'
        return super().save(*args, **kwargs)
    def delete(self, *args, **kwargs):
        if os.path.join(settings.MEDIA_ROOT, self.img.name) == os.path.join(settings.MEDIA_ROOT, 'U'):
            print('first time')
        else:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.img.name))
        
    # def save(self, *args, **kwargs):
    #     if not self.img:
    #         self.img = 'U'
    #     return super().save(*args, **kwargs)
    


    
# Create your models here.
class uploads(models.Model):
    property_image = models.CharField(max_length = 100, blank=True)
    property_name = models.CharField(max_length = 100, blank=True)
    address  = models.CharField(max_length = 100, blank=True)
    location = models.CharField(max_length = 100)
    agent = models.CharField(max_length = 100)





class Agent(models.Model):
    firstname = models.CharField(max_length=32)
    lastname = models.CharField(max_length=32)
    email = models.EmailField()
    password = models.CharField(max_length=100)
    password2 = models.CharField(max_length = 100, null=True, blank=True)
    

@receiver(post_save, sender= settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        UserType.objects.create(user=instance)
        ProfilPicx.objects.create(user=instance)
        

web/moborise/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import uploads, Agent
 
class AgentForm(forms.ModelForm):
    firstname = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'first-name' }))
    lastname = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Surname' }))
    email = forms.EmailField(max_length=254, label='email', help_text='Required. Inform a valid email address.', widget= forms.TextInput
                           (attrs={'placeholder':'Email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'input your password' }))
    password2= forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'confirm password' }))
    class Meta:
        model =Agent
        fields = ('firstname', 'lastname','email','password', 'password2')

    def clean_email(self):
        # Get the email
        email = self.cleaned_data.get('email')

        # Check to see if any users already exist with this email as a username.
        try:
            match = Agent.objects.get(email=email)
        except User.DoesNotExist:
            # Unable to find a user, this is fine
            return email

        # A user was found with this as a username, raise an error.
        raise forms.ValidationError('This email address is already in use.')

class LoginUpForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'username' }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'input your password' }))
    

    class Meta:
        model = Agent
        fields = ('username' , 'password', )


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'First Name' }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Last Name' }))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'username' }))
    email = forms.EmailField(max_length=254, label='email', help_text='Required. Inform a valid email address.', widget= forms.TextInput
                           (attrs={'placeholder':'Email', 'type': 'email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'input your password' }))
    password2= forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'confirm password' }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name','username' , 'email', 'password1', 'password2', )

web/moborise/views.py
from django.shortcuts import render
from .models import uploads, Agent, UserType, Comment, Reply
from django.conf import settings
from django.contrib import messages 
from django.http import HttpResponse
from .forms import AgentForm, LoginUpForm, SignUpForm
from Agent.forms import AgentLoginUpForm, AgentSignUpForm
from Agent.models import Agentuploads
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.template import loader

# Create your views here.
def index(request):
    form = SignUpForm(data=request.POST)
    form2 = LoginUpForm(data=request.POST)
    # loading my forms
    tests = Agentuploads.objects.all().order_by('uploaded_at')

    paginator = Paginator(tests, 8)
    page = request.GET.get('page')
    tests = paginator.get_page(page)

   
    return render(request, 'home.html', {'tests': tests,'form2': form2,'form': form, 'media_url': settings.MEDIA_URL, 'media_root': settings.MEDIA_ROOT,})
@csrf_exempt
def load_index(request):
    page = request.POST.get('page')
    tests = Agentuploads.objects.all()

    paginator = Paginator(tests, 8)
    
    try:
        tests = paginator.page(page)
    except PageNotAnInteger:
        tests = paginator.page(2)
    except EmptyPage:
        tests = paginator.page(paginator.num_pages)

    post_html = loader.render_to_string('home_ajax.html', {'tests' : tests})

    output_data = {
        'post_html' : post_html,
        'has_next' : tests.has_next()
    }
    return JsonResponse(output_data)





    return render(request, 'home_ajax.html', {'tests': tests,'form2': form2,'form': form, 'media_url': settings.MEDIA_URL, 'media_root': settings.MEDIA_ROOT,})

def home(request):
    form = AgentForm(data=request.POST)
    tests = uploads.objects.all()
    context = {'tests': tests,'form': form, 'media_url': settings.MEDIA_URL, 'media_root': settings.MEDIA_ROOT,}
    template = 'home_ajax.html'
    return render(request, template, context)

def loginreq(request):
    form = LoginUpForm(data=request.POST)
    tests = uploads.objects.all()
    context = {'tests': tests,'form': form, 'media_url': settings.MEDIA_URL, 'media_root': settings.MEDIA_ROOT,}
    template = 'login_ajax.html'
    if request.method == 'POST': 
        form = LoginUpForm(data=request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = User.objects.filter(username=username)
        passwordval = User.objects.filter(username=username, password=password)
        if user < 1:
            return JsonResponse({'username_error':'username Does not exist'})

        if passwordval < 1:
            return JsonResponse({'password_error':'password does not match'})

        user = authenticate(username=username, password=password)
              
        login(request, user)
        request.session['username'] = username

        return HttpResponse('successfully registered')

    return render(request, template, context)

def loginUser(request):
    if request.method == 'POST':
        form = LoginUpForm(data=request.POST)
        username = request.POST['username']
        password = request.POST['password']
       
            
        if not User.objects.filter(username=username).exists():
            return JsonResponse({'username_error':'username Does not exist'})

        if not authenticate(username=username, password=password):
            return JsonResponse({'password_error':'password does not match'})

        user = authenticate(username=username, password=password)
                
        login(request, user)
        request.session['username'] = username
        if request.user.profile ==  'Agent':
            return JsonResponse({'success':'success',
            'user':'Agent'})
        return JsonResponse({'success':'success'})
        
        
    else:
        form = LoginUpForm()
      
    return render(request, 'login_ajax.html',  {'form': form,})


@csrf_exempt
def replyy(request):
     
    page = request.POST.get('page')
    print(page)
    comment = Comment.objects.filter(id=page)
    print(comment)
    context = {'comment': comment, 'media_url': settings.MEDIA_URL,}

    template = 'reply.html'
    
    return render(request, template, context)



def search(request):
    q = request.GET.get('q')
    print(q)
    query_string = "SELECT * FROM moborise_uploads WHERE location  LIKE %s ORDER BY id ASC"
    search = uploads.objects.raw(query_string, ('%' + q + '%',))
    
    if len(list(search)) > 0:
        messages.add_message(request, messages.SUCCESS, f'Result for search {q}')
    else:
        messages.warning(request, f'No Result for search {q}')
        
    return render(request, 'search.html',  {'search': search, 'media_url': settings.MEDIA_URL,})

def NewUser(request):
    if request.method == 'POST':
        
        
        firstname = request.POST['name']
        lastname = request.POST['lastname']
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password']
        password = make_password(password1)
        if User.objects.filter(username=username).exists():
            return JsonResponse({'username_error':'username already exists'})

        if User.objects.filter(email=email).exists():
            return JsonResponse({'email_error':'email already in use'})
        
        if len(password1) < 5:
            return JsonResponse({'password_error':'password should be greater than 5'})
        
        user = User.objects.create(
            first_name = firstname,
            last_name = lastname,
            username = username,
            email = email,
            password = password,
            
        )
        user =  User.objects.get(username=request.POST['username'],)
        profile = user.profile # because of signal and one2one relation
        profile.role = 'user'
        profile.save()
    
        
        return JsonResponse({'success':'success'})


@csrf_exempt
def comment(request, property_id, username):
    comment = request.POST['comment']
    time = request.POST['time']
    user = Comment.objects.create(
            text = comment,
            time= time,
            post_id = property_id,
            author = request.user,
            to = username,
            Username = request.user.get_full_name(),
            
        )
    
    
    post_html = loader.render_to_string('comment.html', {'comment' : user})

    output_data = {
        'post_html' : post_html,
    }
    return JsonResponse(output_data)

@csrf_exempt
def send_reply(request, comment_id, username):
    reply = request.POST['comment']
    time = request.POST['time']
    print(reply)
    user = Reply.objects.create(
            reply = reply,
            time= time,
            rep_id = comment_id,
            Username = request.user.get_full_name(),
            to = username,
        
        )
    
    
    post_html = loader.render_to_string('send_reply.html', {'comment' : user})

    output_data = {
        'post_html' : post_html,
    }
    return JsonResponse(output_data)

@csrf_exempt
def commentlist(request, property_id, username):

    comment = Comment.objects.filter(post_id=property_id)
    post_html = loader.render_to_string('comment.html', {'comment' : comment})

    output_data = {
        'post_html' : post_html,
    }
    return JsonResponse(output_data)



def show_property(request, property_id, username):
    form = SignUpForm(data=request.POST)
    form2 = LoginUpForm(data=request.POST)
    user = get_object_or_404(User, username=username,)
    
    propertyy = Agentuploads.objects.get(id=property_id)
    comment = Comment.objects.filter(post_id=property_id)
    
    return render(request, 'view_property.html', {'form2': form2,'comment': comment,'form': form,"person":user,'property': propertyy, 'media_url': settings.MEDIA_URL,})








def signup(request):
    form = SignUpForm(data=request.POST)
    tests = uploads.objects.all()
    context = {'tests': tests,'form': form, 'media_url': settings.MEDIA_URL, 'media_root': settings.MEDIA_ROOT,}
    template = 'signup.html'
    

    return render(request, template, context)

def logout_request(request):
    
    
    
    logout(request)
    
    return redirect('/')

web/moborise/templates/comment.html
<li>
                            <div class="commenterImage">
                              <img src="http://placekitten.com/50/50" />
                            </div>
                            <div class="commentText">
                            
                                <p class=""><b style="font-size: 20px;">{{ comment.author }}   </b>{{ comment.text}} <a id="reply{{comment.id}}" href="" data-page="{{ comment.id }}">  reply</a></p> <span class="date sub-text">{{ comment.time}}</span>

                            </div>
                        </li>

web/moborise/templates/comment_ajax.html
<ul class="commentList">
                {% for comment in comment %}

                        <li>
                            <div class="commenterImage">
                              <img src="http://placekitten.com/50/50" />
                            </div>
                            <div class="commentText">
                            
                                <p class="">{{ comment.text}} <a id="reply{{comment.id}}" href="" data-page="{{ comment.id }}">  reply</a></p>  <span class="date sub-text">{{ comment.time}}</span>

                            </div>
                        </li>
                    <script>
                        $("#reply{{comment.id}}").click(function(e){
                            e.preventDefault();
                            var link = $(this);
                            var page = link.data('page');
                          $.ajax({

                                      type: 'post',
                                      url: '{% url 'reply'  %}',
                                    
                                      data:{
                                        'page': page,
                                        
                                      },
                                      
                                      success:function(response){

                                        if (response.has_next){
                                          link.data('page', page+1);
                                        } else{
                                          link.hide();
                                          $('#no_more').show();
                                        }

                                
                                        $('.actionBox').html(response)
                                        
                                      
                                      },
                                      error: function(data) {
                                        $('#Notifications').html(data.message).css('color', 'red');
                                      
                                      }
                                    });

                      }); 

                    </script>
                {% endfor %}
                      </ul>
                    <form id="commentbox" class="form-inline" role="form">
                        <div class="form-group">
                            <input autocomplete='off' style="width: 100%;" id="commentss" class="form-control" type="text" placeholder="Your comments" />
                        </div>
                        <div class="form-group">
                            <button class="btn btn-default">Add</button>
                        </div>
                    </form>

web/moborise/templates/home_ajax.html
{% load static %}

{% for property in tests %}

    <div class="col-lg-3 col-md-3 col-sm-6">
                        <div  class="card mb-4">
                            <a  href="{% url 'view_property' property.id property.username %}">
                                <div class="card-img-top"
                                    ><img src="{{property.file.url}}" style=" height:150px;width:100% "></div>
                            
                            <div  class="card-body">
                            <span style='font-weight: 20px;'>₦{{property.price}},000</span>
                                <br>
                                <span  id="view{{ property.id }}"  style="text-size:10px; color: black;"><span style='font-weight: 20px;'>Location: </span>{{property.property_Location}}
                                <br>
                                <span style='font-weight: 20px;'>Property Name: </span>{{property.property_Name}}</span></a>
                                <br>
                                <span class="text-warning">Not verified</span>
                                
                            </div>
                        </div>
                        <!-- /.card -->
              
    </div>                

    <script src="{% static 'jquery.js' %}"></script>

              {% endfor %}

web/moborise/templates/login_ajax.html
        <span class="close">&times;</span>
        
        <h1>Login</h1>
        {% load static %}
            <form id="LoginForm" action="{% url 'UserLogin'  %}">
            {% csrf_token %}
            <p>Username</p>
              {{ form.username }}
              <span id='usernamee_error'></span>
              <p>Password</p>
              {{ form.password }}
              <span id='password_error'></span>
          
            
              <span id='message'></span>
              <input  id="Login"  type="submit" name="submit" value="Login">
              <h1 id="Notifications"></h1>
                <div class="ajaxProgress" style="display:none; margin-top: -30px; text-align:center; ">
    <h3>Please Wait</h3>
    <img src="{% static 'loading.gif' %}">
  </div>
</div>
            </form>

            <a href="#">Lost your password</a><br>
				    <a href="" id="signup" name="SignUp">Don't have an account ?</a>



         
 

web/moborise/templates/reply.html
<ul class="commentList">
<button id='back' style="padding: 10px; width: 100px; border-radius: 10px; border: none;">Back</button>
                    {% for comment in comment %}

                        <li>
                            <div class="commenterImage">
                              <img src="http://placekitten.com/50/50" />
                            </div>
                            <div class="commentText">
                            
                                <p class=""><h5>{{ comment.text}}</h5> </p>  <span class="date sub-text">{{ comment.time}}</span>

                            </div>
                        </li>
                        {% for reply in comment.reply.all %}
                        <li style="margin-left: 20px;">
                            <div class="commenterImage">
                              <img src="http://placekitten.com/50/50" />
                            </div>
                            <div class="commentText">
                            
                                <p class=""><b style="font-size: 15px;">{{ reply.Username }} </b>{{ reply.reply}} </p>  <span class="date sub-text">{{ comment.time}}</span>

                            </div>
                        </li>
                        {% endfor %}
                        <script>
                                  $("#back").click(function(e){
                                      
                                      window.location.reload();

                                }); 

                                $(document).on('submit', '#replybox', function(e){
              e.preventDefault();

              const monthNames = ["January", "February", "March", "April", "May", "June","July", "August", "September", "October", "November", "December"];
             var comment = $('#replys').val();

            var dt = new Date($.now());
            var hours = dt.getHours();
            if (hours >= 12) {
                  strampm= " PM";
              } else {
                  strampm= " AM";
              }
              hours = hours % 12;
              if (hours == 0) {
                  hours = 12;
              }
            var time = (monthNames[dt.getMonth()])  + " " 
                + dt.getDate() + " ,"
                + dt.getFullYear() + " ,"  
                + hours + ":"  
                + dt.getMinutes() + ":" 
                + dt.getSeconds() + strampm;

              
              $("#replybox")[0].reset();
              $.ajax({

                type: 'POST',
                url: '{% url 'send_reply' comment.id comment.author_id %}',
                data:{
                  comment: comment,
                  time: time,
                },
                cache: false,
                
              
                
                success:function(response){
                
                  
                  $('.commentList').append(response.post_html)
                  
                
                },
                error: function(data) {
                  $('#Notifications').html(data.message).css('color', 'red');
                
                }
              });
            }); 


                        </script>
                    {% endfor %}
                      </ul>
                      <form id="replybox" class="form-inline" role="form">
                        <div class="form-group">
                            <input autocomplete='off' style="width: 100%;" id="replys" class="form-control" type="text" placeholder="Your reply" />
                        </div>
                        <div class="form-group">
                            <button class="btn btn-default">Add</button>
                        </div>
                    </form>
                    

web/moborise/templates/send_reply.html
<li style="margin-left: 20px;">
                            <div class="commenterImage">
                              <img src="http://placekitten.com/50/50" />
                            </div>
                            <div class="commentText">
                            
                                <p class=""><b style="font-size: 15px;">{{ comment.Username }} </b>{{ comment.reply}} </p>  <span class="date sub-text">{{ comment.time}}</span>

                            </div>
                        </li>

web/moborise/templates/view_property_ajax.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="">
  <a class="navbar-brand" href="/"><img height="30" width="100" src="{% static 'molite1.jpg' %}"></a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navb">
    <ul class="navbar-nav justify-content-center mr-auto">
      <li><a class="nav-link" id="home" href="">Home</a></li>
        <li><a class="nav-link" href="#">Locations</a></li>
        <li><a class="nav-link" href="#">Vacancies</a></li>
        <li><a class="nav-link" href="#">Info</a></li>
        <li><a class="nav-link" class="nav-link" href="#">Sign up or Login </a></li>
        <li><a class="nav-link" href="#">About us</a></li>
    </ul>
    <form action="/search" class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" required type="search" autocomplete="off"  name="q" aria-label="Search" placeholder="Search for vacancies...">
      <button class="btn btn-success my-2 my-sm-0" style="background: #000;" type="button">Search</button>
    </form>
  </div>
</nav>


<div class="container">
  <div class="row">
    <div class="col-sm-12 ">
      <div class="view-port">
          <div class="image-port">
            <img src="{{media_url}}{{property.property_image}}" style=" ">
          </div>
          <div class = "view-info">
            <h3>{{property.property_name}}</h3>
            <h5>{{property.address}}</h5>
            <h5>{{property.location}}</h5>
            <h5>Agent : {{property.agent}}</h5>
            <a href="tel:+62896706255135">Call {{property.agent}} at +62-896-7062-55135</a>
          </div>
      </div>
    </div>
  </div>

</div>

 <script>





    $('#id_password, #id_password2').on('keyup', function () {

      if ($('#id_password').val() == $('#id_password2').val()) {
        
        $('#message').html('Matching').css('color', 'green');
        
        
        
      } else 
        $('#message').html('Not Matching').css('color', 'red');
      
        
    });




    $(document).on('submit', '#NewAgent', function(e){
              e.preventDefault();
              

              
              $.ajax({

                type: 'POST',
                url: '{% url 'NewAgent'  %}',
                data:{
                  name: $('#id_firstname').val(),
                  lastname:$('#id_lastname').val(),
                  email:$('#id_email').val(),
                  password:$('#id_password').val(),
                
                  csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                },
              
                
                success:function(data){
                  $('#submit').html('').css( 'display', 'none');
                  $('#Notifications').html('Successfully Signup').css('color', 'green');
                
                },
                error: function() {
                  $('#Notifications').html('something went wrong... Try again').css('color', 'red');
                
                }
              });
            });

$('#home').click(function(e) {
   e.preventDefault();

            $.ajax({
                method: 'GET',
                url: '{% url 'home'  %}',
                
                success: function (data) {
                    //window.location.href = '{% url 'view_property' property.id %}'; 
                    $('#content').html(data)
                },
                error: function(data){
                    return false;
                }
            });
        });


    </script>